### ISSUE TITLE
Sidebar bleeding through 😬

### ISSUE THREAD

**Issue by Bonitoflakes** [Bonitoflakes/clockify#7]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/75728765/236678619-82a4ff45-48fd-4473-9d4e-15f6f83625a7.png">

**Comment by kumarhites** [comment]
Have you checked for z-index value?

**Comment by Bonitoflakes** [comment]
Yeah, was able to finally figure it out, the overall parent's z-index had to be increased, which was shocking.
